# NUMPY

# Working with Numpy - for mathematical operations

##numpy means numerical python
#import numpy as np

In [3]:
import numpy as np

### shape

In [ ]:
a=np.array([1,2,3,4,5])
print(a)
print(a.shape)
type(a)

In [ ]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)
type(b)

In [ ]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

### create array of Zeros,Ones array

In [7]:
x=np.zeros((3,3))
print(x)

x1=np.zeros((3,3),dtype='int')
print(x1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
xy=np.ones((3,3)) #by default it is float
print(xy)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
#we can change to int also
xy1=np.ones((3,3),dtype='int')
print(xy1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### Array of some constants

In [ ]:

c=np.full((3,3),10)
    #rows,columns  #number which is constnt
print(c)

### identity  Matrix - size/Square Matrix

In [ ]:

d=np.eye(5) #5 rows & columns
print(d)

### Random matrix

In [4]:
#random matrix
r=np.random.random((2,3))
                  #rows,columns
print(r)


#we can update the matrix also
print(r[:,1]) #slicing

  #row,colummn
r[1,1:]=5
print(r)


[[0.23427917 0.75722042 0.47250206]
 [0.78904034 0.36786262 0.48008923]]
[0.75722042 0.36786262]
[[0.23427917 0.75722042 0.47250206]
 [0.78904034 5.         5.        ]]


dtype('float64')

### datatype

In [8]:
#DataTypes
r.dtype

dtype('float64')

## Mathematical Operations

In [10]:
x=np.array([[1,1],[2,2]])
y=np.array([[2,2],[1,1]])
print(x+y) #arithmetic operation

[[3 3]
 [3 3]]


In [11]:
#using in-bulit function(addition)
print(np.add(x,y))

[[3 3]
 [3 3]]


In [14]:
x=np.array([[1,1],[2,2]])  #subtraction
y=np.array([[2,2],[1,1]])
print(x-y) 
print(np.subtract(y,x)) #inbulit

[[-1 -1]
 [ 1  1]]
[[ 1  1]
 [-1 -1]]


In [16]:
print(x*y) #multiplication
print(np.multiply(x,y))

[[2 2]
 [2 2]]
[[2 2]
 [2 2]]


In [15]:
print(x/y) #divison
print(np.divide(x,y))

[[0.5 0.5]
 [2.  2. ]]
[[0.5 0.5]
 [2.  2. ]]


In [17]:
#matrix Multiplication / Dot products

print(x)
print(y)
print(x.dot(y))
print(np.dot(x,y))

[[1 1]
 [2 2]]
[[2 2]
 [1 1]]
[[3 3]
 [6 6]]
[[3 3]
 [6 6]]


## Broadcasting is possible in Numpy

In [18]:
x=np.array([[1,1],[2,2]])
y=np.array([[2,2]])
print(x+y) 

[[3 3]
 [4 4]]


## Multiplication (Dot Product) of Vectors -> Scalar


In [19]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b)) #[1 2 3 4] [1\n 2\n 3\n 4\n]
                #1*1+2*2+3*3+4*4
                # (1+2+3+4)**2
                #30 is the answer

30


In [20]:
print(a)

[1 2 3 4]


In [21]:
#sum of an array
a=np.array([1,2,3,4])
print(a)
print(sum(a))

[1 2 3 4]
10


In [24]:
print(np.sum(a))
print(np.sum(a,axis=0))

10


In [27]:
x=np.array([[1,1],[2,2]])
y=np.array([[2,2]])
print(x)
print(np.sum(x,axis=0))
 
print(np.sum(x,axis=1)) #[ 1 1 ] =2
                        #[ 2 2 ]  =4
    #[ 2 4 ]

[[1 1]
 [2 2]]
[3 3]
[2 4]


## Stacking of arrays

In [28]:
#print(a)
b=a*2
print(b)

[1 2 3 4]
[2 4 6 8]


In [29]:
np.stack((a,b),axis=0)

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [36]:
#np.stack((a,b),axis=1)


In [37]:
print(a)

[[1 2]
 [2 4]
 [3 6]
 [4 8]]


## Reshape the array

In [38]:

          #rows,columns
a=a.reshape((2,4))
print(a)


[[1 2 2 4]
 [3 6 4 8]]


In [39]:
a=a.reshape((8,1))
print(a)

[[1]
 [2]
 [2]
 [4]
 [3]
 [6]
 [4]
 [8]]


## Numpy Random Module

In [42]:
#generate the numbers from 0 to n-1
n=int(input("enter the number : "))
a=np.arange(n)
print(a)

enter the number : 6
[0 1 2 3 4 5]


In [48]:
x=np.arange(11)+5  #starts from 0 to 10 and each added with 5
print(x)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [51]:
np.random.shuffle(x) #each time it will shuffles the data
print(x)


[ 7  5  9 14 15 10  8 12 11 13  6]


In [53]:
x=np.random.randn(2,3) #random values 
              #rows,columns
print(x)

[[-1.95047255  0.13978978  0.18357509]
 [ 1.82312622  1.04189429  1.92110777]]


In [54]:
x=np.random.randint(5,10,3) #random values 
              #rows,columns
print(x)

[5 6 5]


### Random pick one element from an array

In [56]:
A=np.random.choice([1,2,3,4,5,6])
print(A)

3


## Numpy Functions - Statistics

In [62]:
#min function
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3]
 [4 5 6]]
1
[1 2 3]
[1 4]


In [67]:
#Mean /avg function
a=np.array([1,2,3])
b=np.array([4,5,6])
c=sum(a)/3
print(c)
print(np.mean(a))
print(np.mean(a,axis=0))
#print(np.mean(a,axis=1))

2.0
2.0
2.0


In [70]:
#median (sort and middle value )
a=np.array([1,2,3,4])
b=np.array([1,2,3])
print(np.median(a))
print(np.median(b))

2.5
2.0
